# UTS-3 My Stories for You

Masa-masa menjelang akhir semester enam menjadi titik balik bagi saya dan teman-teman saya. Waktu terasa bergerak cepat, dan kami dihadapkan pada satu tugas wajib yang mendesak yaitu mencari tempat magang untuk konversi SKS Kerja Praktik (KP). Kami semua panik, pertanyaan "Dapat di mana?" dan "Bagaimana kalau tidak dapat?" sudah menjadi kebiasaan harian, memaksa saya untuk segera bertindak. Saya melakukan langkah standar yang dilakukan teman-teman saya, seperti menyiapkan portofolio, aktif di job portal, hingga menghubungi senior untuk mencari koneksi. Di tengah kesibukan akademik menjelang UAS, saya mendapatkan satu prospek dari rekomendasi Ayah, tetapi tawaran ini langsung menimbulkan sebuah dilema. Durasi magang yang ditawarkan tidak sesuai dengan peraturan minimal yang ditetapkan kampus. Meskipun ini adalah satu-satunya kemajuan paling jelas, keraguan terus membayang-bayangi. Namun, dengan pegangan pada nasihat senior bahwa "lowongan baru akan lebih banyak menjelang akhir semester," saya terus mencari, mencoba menjaga harapan di tengah ketidakpastian.

Setelah masa ujian berlalu, harapan sempat meninggi ketika saya mendapatkan kabar baik dari salah satu perusahaan yang saya lamar melalui daftar magang yang diberikan di himpunan saya. Sayangnya, proses perbincangan berhenti di tengah jalan, tanpa kejelasan. Merasa waktu semakin sempit, saya kembali menindaklanjuti tawaran dari Ayah, yang menjadwalkan magang dimulai 1 Juli. Walaupun dibayangi ketidaksesuaian durasi dengan aturan kampus, saya tetap datang ke kantor di hari pertama. Kedatangan saya disambut kejutan kecil, teman magang saya ternyata adalah teman SMP lama, yang sedikit banyak meredakan ketegangan di hari pertama. Namun, di balik lingkungan kerja yang ramah, konflik batin saya belum usai. Perusahaan ini hanya menawarkan satu bulan magang, kurang dari syarat minimal dua bulan KP ITB. Selama sebulan pertama magang, saya tetap mencari tempat lain yang durasinya pasti memenuhi syarat kampus. Pencarian ini membuahkan hasil, di mana seorang teman memberikan rekomendasi lowongan yang akhirnya mengirimkan saya surat penawaran (offering letter) dengan durasi enam bulan work from office. Ini adalah kabar baik yang sangat saya harapkan, tetapi ia membawa konflik baru, durasi enam bulan terlalu panjang, mengancam kesibukan saya di semester 7 serta komitmen saya di himpunan. Saya sadar, saya tidak bisa terus mencari tempat yang 100% sesuai dengan semua aturan, saya harus berani menghadapi aturan itu sendiri.

Momen penemuan diri terjadi di tengah kebimbangan menghadapi tawaran enam bulan tersebut. Saya menyadari bahwa nilai saya komitmen dan hasil kerja sebenarnya layak untuk dinegosiasikan. Setelah berkonsultasi dengan orang terdekat, saya mengambil langkah yang krusial: menegosiasikan durasi magang menjadi tiga bulan. Beruntung, negosiasi tersebut diterima. Dengan keberanian untuk tidak hanya menerima atau menolak, saya berhasil mengubah aturan main, mengamankan tempat magang yang sesuai untuk KP tanpa mengorbankan semester akhir saya. Setelah menyelesaikan magang di perusahaan pertama, saya beralih ke tempat magang yang baru ini, menyeimbangkan peran mahasiswa, anggota himpunan, dan intern. Pengalaman ini mengajarkan saya bahwa, jangan pernah menyerah dan selalu sabar dalam keadaan apapun. Tetaplah berdoa dan berpikir positif terhadap semua kondisi yang diberikan. Berpikirlah lebih terbuka terhadap apa yang sedang terjadi dengan diri kita, bisa jadi kesempatan yang datang tak terduga adalah doa yang dulu pernah kita lantunkan.